= The Cassandra Query Language (CQL)

This document describes the Cassandra Query Language
(CQL) version 3.
Note that this document describes the last version of the language.
However, the xref:cql/changes.adoc[changes] section provides the differences between the versions of CQL since version 3.0.

CQL offers a model similar to SQL.
The data is stored in *tables* containing *rows* of *columns*.
For that reason, when used in this document, these terms (tables, rows and columns) have the same definition that they have in SQL.

[IMPORTANT]
====
SQL developers should read these Cassandra-specific differences first:

* `INSERT` is an upsert: it creates a row if it does not exist and overwrites it if the primary key already exists.
* CQL does not support joins or arbitrary sub-queries.
* Most queries must specify the partition key. When they do not, `ALLOW FILTERING` may be required and can be expensive.
* The primary key controls both data distribution and row order, so table design starts from the query pattern.
* There is no general-purpose full table scan path that behaves like SQL by default.
====

* xref:cql/definitions.adoc[Definitions]
* xref:cql/types.adoc[Data types]
* xref:cql/ddl.adoc[Data definition language]
* xref:cql/dml.adoc[Data manipulation language]
* xref:Cassandra:cassandra:developing/cql/dynamic-data-masking.adoc[Dynamic data masking]
* xref:Cassandra:cassandra:developing/cql/operators.adoc[Operators]
* xref:Cassandra:cassandra:developing/cql/indexing/indexing-concepts.adoc[Indexing]
* xref:Cassandra:cassandra:developing/cql/mvs.adoc[Materialized views]
* xref:cql/functions.adoc[Functions]
* xref:Cassandra:cassandra:developing/cql/json.adoc[JSON]
* xref:cql/security.adoc[CQL security]
* xref:cql/triggers.adoc[Triggers]
* xref:cql/constraints.adoc[Constraints]
* xref:Cassandra:cassandra:developing/cql/appendices.adoc[Appendices]
* xref:cql/changes.adoc[Changes]
